name: Build Qt Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-mac:
    name: macOS Build
    runs-on: macos-14
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install FFmpeg & OpenCV via Homebrew
        run: |
          brew install ffmpeg@4 opencv

      - name: Download 3rd_party.tar.gz
        run: |
          curl -L -o 3rd_party.tar.gz https://github.com/Areay7/LearnCode/releases/download/v1.1.1/3rd_party.tar.gz
          tar -xzf 3rd_party.tar.gz

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          target: 'desktop'
          arch: 'clang_64'

      - name: Build Project
        run: |
          qmake your.pro
          make -j$(sysctl -n hw.ncpu)

  build-linux:
    name: Ubuntu Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y libx11-dev libgl1-mesa-dev libpulse-dev

      - name: Download 3rd_party.tar.gz
        run: |
          curl -L -o 3rd_party.tar.gz https://github.com/Areay7/LearnCode/releases/download/v1.1.1/3rd_party.tar.gz
          tar -xzf 3rd_party.tar.gz

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          target: 'desktop'
          arch: 'gcc_64'

      - name: Build Project
        run: |
          qmake your.pro
          make -j$(nproc)

  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download and extract 3rd_party.tar.gz
        run: |
          curl -L -o 3rd_party.tar.gz https://github.com/Areay7/LearnCode/releases/download/v1.1.1/3rd_party.tar.gz
          tar -xzf 3rd_party.tar.gz

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          target: 'desktop'
          arch: 'win64_msvc2019_64'  # 根据你使用的 MSVC 版本修改

      - name: Build Project (Windows)
        shell: cmd
        run: |
          qmake your.pro
          nmake
