name: Build Qt CMake Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    name: macOS Build
    runs-on: macos-14
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies (FFmpeg & OpenCV)
        run: |
          brew update
          brew install ffmpeg opencv

      - name: Download 3rd_party
        run: |
          curl -L -o 3rd_party.tar.gz https://github.com/Areay7/LearnCode/releases/download/v1.1.1/3rd_party.tar.gz
          tar -xzf 3rd_party.tar.gz

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          target: 'desktop'
          arch: 'clang_64'

      - name: Configure with CMake
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=$Qt6_DIR

      - name: Build
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)

  build-linux:
    name: Ubuntu Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libx11-dev libgl1-mesa-dev libpulse-dev

      - name: Download 3rd_party
        run: |
          curl -L -o 3rd_party.tar.gz https://github.com/Areay7/LearnCode/releases/download/v1.1.1/3rd_party.tar.gz
          tar -xzf 3rd_party.tar.gz

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          target: 'desktop'
          arch: 'gcc_64'

      - name: Configure with CMake
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=$Qt6_DIR

      - name: Build
        run: |
          cd build
          make -j$(nproc)

  build-windows:
    name: Windows Build (MSVC)
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download 3rd_party
        run: |
          curl -L -o 3rd_party.tar.gz https://github.com/Areay7/LearnCode/releases/download/v1.1.1/3rd_party.tar.gz
          tar -xzf 3rd_party.tar.gz

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH="%Qt6_DIR%" -G "NMake Makefiles"

      - name: Build with NMake
        run: |
          cd build
          nmake
